/* English interface labels. Learning translations remain in content.js. */
window.TT_UI = {
  scenes: {
    airport: { name: 'Airport & immigration', short: 'Airport', desc: 'Check-in, security, arrivals' },
    hotel: { name: 'Hotels', short: 'Hotel', desc: 'Reservations, rooms, check-out' },
    food: { name: 'Dining', short: 'Dining', desc: 'Tables, orders, the bill' },
    shopping: { name: 'Shopping', short: 'Shopping', desc: 'Sizes, prices, returns' },
    spa: { name: 'Spa & massage', short: 'Spa', desc: 'Bookings, treatments, preferences' },
    transport: { name: 'Getting around', short: 'Transit', desc: 'Directions, taxis, public transport' },
    help: { name: 'Help', short: 'Help', desc: 'Medical help, lost belongings' },
    forms: { name: 'Travel notes', short: 'Forms', desc: 'Arrival forms, key terms' }
  },
  tasks: {
    'check-in': { title: 'Check in for your flight', desc: 'Terminals, passports, online check-in' },
    'baggage-seat': { title: 'Check bags, choose seats', desc: 'Baggage limits, carry-ons, sitting together' },
    security: { title: 'Go through security', desc: 'Trays, laptops, personal items' },
    boarding: { title: 'Find your gate', desc: 'Boarding times, gate changes' },
    'flight-change': { title: 'Handle flight changes', desc: 'Delays, cancellations, missed connections' },
    transfer: { title: 'Catch your connection', desc: 'Transfer desks, immigration, checked bags' },
    immigration: { title: 'Answer immigration questions', desc: 'Travel plans, accommodation, return flights' },
    'baggage-claim': { title: 'Collect your bags', desc: 'Carousels, missing or damaged bags' },
    'hotel-check-in': { title: 'Check in to your hotel', desc: 'Booking name, guests, length of stay' },
    'room-preference': { title: 'Choose your room', desc: 'Bed types, quiet rooms, non-smoking rooms' },
    'hotel-payment': { title: 'Check rates and deposits', desc: 'Prepaid bookings, card holds, upgrades' },
    'hotel-info': { title: 'Ask about hotel services', desc: 'Breakfast, check-out times, Wi-Fi, key cards' },
    'early-check-in': { title: 'Arrive before check-in', desc: 'Early arrival, luggage storage, collection' },
    'room-problem': { title: 'Report a room issue', desc: 'Air conditioning, hot water, noise, keys' },
    'check-out': { title: 'Check out', desc: 'Late check-out, bills, deposits' },
    table: { title: 'Get a table', desc: 'Reservations, waiting times, seating' },
    menu: { title: 'Ask for recommendations', desc: 'Local dishes, ingredients, portion sizes' },
    order: { title: 'Place your order', desc: 'Menu choices, quantities, sharing' },
    preferences: { title: 'Adjust your order', desc: 'Spice levels, ingredients, ice, sugar' },
    'allergy-food': { title: 'Explain a food allergy', desc: 'Allergens, ingredients, cross-contact' },
    'during-meal': { title: 'Ask for help mid-meal', desc: 'Missing dishes, wrong orders, cutlery' },
    takeaway: { title: 'Order food to go', desc: 'Takeaway orders, leftovers, containers' },
    bill: { title: 'Ask for the bill', desc: 'Card payments, split bills, service charges' },
    'mall-directions': { title: 'Find your way around', desc: 'Shops, food courts, lifts, toilets' },
    browse: { title: 'Browse and ask for help', desc: 'Shop assistants, colours, display items' },
    'try-on': { title: 'Try it on', desc: 'Fitting rooms, sizes, fit' },
    discount: { title: 'Ask about discounts', desc: 'Sale prices, multi-buy offers, conditions' },
    decision: { title: 'Buy or keep looking', desc: 'Buying, declining, putting items on hold' },
    'shop-payment': { title: 'Pay for your purchase', desc: 'Bags, membership, gift wrapping, receipts' },
    returns: { title: 'Return or exchange items', desc: 'Return policies, deadlines, receipts' },
    'spa-book': { title: 'Book treatments for two', desc: 'Availability, duration, starting together' },
    'spa-arrival': { title: 'Choose a treatment', desc: 'Treatment menus, prices, booking details' },
    'spa-pressure': { title: 'Adjust the pressure', desc: 'Gentler, firmer, areas to avoid' },
    'spa-change': { title: 'Change your booking', desc: 'Rescheduling, cancellations, fees' },
    directions: { title: 'Ask for directions', desc: 'Maps, landmarks, walking distance' },
    taxi: { title: 'Take a taxi', desc: 'Destinations, pick-up points, fares' },
    'public-transport': { title: 'Take public transport', desc: 'Tickets, routes, stops, connections' },
    medical: { title: 'Get medical help', desc: 'Symptoms, doctors, emergencies' },
    'lost-items': { title: 'Report a lost item', desc: 'Passports, phones, police reports' }
  },
  variants: {
    '先找柜台': 'Find the counter',
    '我已经在线值机了': 'Already checked in online',
    '行李额度': 'Baggage allowance',
    '座位偏好': 'Seat preferences',
    '不确定时先问': 'Check what to do',
    '登机口可能变了': 'Gate changes',
    '没听清数字': 'Check the number',
    '行程发生变化': 'Changes to your flight',
    '把流程问清楚': 'Check the transfer process',
    '回程和同行人': 'Return travel and companions',
    '需要工作人员帮助': 'Ask staff for help',
    '订单信息有误': 'Incorrect booking details',
    '说明预订渠道': 'Where you booked',
    '其他偏好': 'Other room preferences',
    '付钱之前问清楚': 'Check before paying',
    '入住时顺便问': 'Questions at check-in',
    '晚点回来': 'Collect your bags later',
    '换成你的实际问题': 'Other room issues',
    '时间和费用': 'Timing and charges',
    '座位与预订': 'Seating and reservations',
    '看不懂菜名时': 'Ask about a dish',
    '一起分着吃': 'Share a dish',
    '换一种饮料': 'Choose another drink',
    '暂时点这些': 'Finish your order',
    '食物偏好': 'Food preferences',
    '饮料偏好': 'Drink preferences',
    '替换过敏原': 'Specify your allergy',
    '其他需求': 'Other requests',
    '吃不完带走': 'Take leftovers with you',
    '分开付或账单有误': 'Split or check the bill',
    '找设施': 'Find facilities',
    '有明确需求时': 'Ask for a specific item',
    '找到合适的尺码': 'Find the right size',
    '把优惠问清楚': 'Check the offer',
    '做出决定': 'Make a decision',
    '付款时的需求': 'Requests at checkout',
    '已经买了想换': 'Exchange a purchase',
    '时间没有空位': 'Try another time',
    '预约前发消息': 'Enquire before booking',
    '到店后确认': 'Confirm on arrival',
    '随时表达感受': 'Speak up during treatment',
    '取消预约': 'Cancel your booking',
    '确认距离和方向': 'Check distance and direction',
    '上车前确认': 'Check before getting in',
    '确认路线': 'Check your route',
    '紧急求助': 'Emergency help',
    '说明常见症状': 'Describe your symptoms',
    '请求协助': 'Ask for assistance'
  }
};
